name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag wifi-bill-generator:$(date +%s)
        docker run --name wifi-bill-generator wifi-bill-generator # Run the container to generate static files
        docker cp wifi-bill-generator:/app/_site ./_site # Copy the generated static files to the runner environment

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './_site' # The directory containing the static files to deploy

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

